name: szakdoga
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flut_grouped_buttons: ^0.0.9
  get: ^4.6.5
  cupertino_icons: ^1.0.6
  flutter_heatmap_calendar: ^1.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
